(defun init--install-packages ()
  (packages-install
   (cons 'ace-jump-mode melpa)
   (cons 'bookmark+ melpa)
   (cons 'browse-kill-ring melpa)
   (cons 'change-inner melpa)
   (cons 'dash melpa)
   (cons 'diminish melpa)
   (cons 'dired-details melpa)
   (cons 'elisp-slime-nav melpa)
   (cons 'eproject melpa)
   (cons 'exec-path-from-shell melpa)
   (cons 'expand-region melpa)
   (cons 'feature-mode melpa)
   (cons 'find-file-in-project melpa)
   (cons 'fold-this melpa)
   (cons 'frame-cmds melpa)
   (cons 'frame-fns melpa)
   (cons 'geiser marmalade)
   (cons 'golden-ratio melpa)
   (cons 'icicles melpa)
   (cons 'ido-ubiquitous melpa)
   (cons 'iedit melpa)
   (cons 'jade-mode melpa)
   (cons 'js2-mode melpa)
   (cons 'js2-refactor melpa)
   (cons 'jump melpa)
   (cons 'jump-char melpa)
   (cons 'key-chord melpa)
   (cons 'magit melpa)
   (cons 'maxframe melpa)
   (cons 'multifiles melpa)
   (cons 'multiple-cursors melpa)
   (cons 'perspective melpa)
   (cons 's melpa)
   (cons 'sicp melpa)
   (cons 'smartparens melpa)
   (cons 'smex melpa)
   (cons 'smooth-scrolling melpa)
   (cons 'undo-tree melpa)
   (cons 'yaml-mode melpa)
   (cons 'yasnippet melpa)))

(condition-case nil
    (init--install-packages)
  (error
   (package-refresh-contents)
   (init--install-packages)))

(provide 'install-packages)
